import type { ReportLanguage } from '../types/analysis';

export const normalizeReportLanguage = (value?: string | null): ReportLanguage =>
  value === 'en' ? 'en' : 'zh';

const REPORT_TEXT = {
  zh: {
    keyInsights: 'Key insights',
    noAnalysisSummary: 'No analysis summary',
    actionAdvice: 'Action advice',
    noAdvice: 'No advice',
    trendPrediction: 'Trend prediction',
    noPrediction: 'No prediction',
    marketSentiment: 'Market sentiment',
    strategyPoints: 'Strategy levels',
    sniperLevels: 'Entry levels',
    idealBuy: '理想Buy',
    secondaryBuy: '二次Buy',
    stopLoss: 'Stop-loss price',
    takeProfit: 'Take-profit target',
    noValue: '—',
    newsFeed: 'News feed',
    relatedNews: 'Related news',
    refresh: 'Refresh',
    retry: 'Retry',
    dismiss: 'Close',
    details: 'View details',
    loadingNews: 'Loading news...',
    noNews: 'NoneRelated news',
    noNewsDescription: 'Refresh later to get the latest news.',
    openLink: 'Open',
    transparency: 'Transparency',
    traceability: 'Data traceability',
    rawResult: 'Raw analysis result',
    analysisSnapshot: 'Analysis snapshot',
    copy: 'Copy',
    copied: '已Copy',
    recordId: '记录 ID',
    fullReport: 'FullAnalysisReport',
    loadingReport: 'Loading report...',
    loadReportFailed: 'Loading report failed',
    copyMarkdownSource: 'Copy Markdown 源码',
    copyPlainText: 'Copy纯文本',
    analysisModel: 'AnalysisModels',
    fearGreedIndex: '恐惧贪婪指数',
    boardLinkage: '板块联动',
    relatedBoards: '关联板块',
    leadingBoard: '领涨',
    laggingBoard: '领跌',
    neutralBoard: 'Neutral',
    reanalyze: '重新Analysis',
  },
  en: {
    keyInsights: 'KEY INSIGHTS',
    noAnalysisSummary: 'No analysis summary yet',
    actionAdvice: 'Action Advice',
    noAdvice: 'No advice yet',
    trendPrediction: 'Trend Outlook',
    noPrediction: 'No forecast yet',
    marketSentiment: 'Market Sentiment',
    strategyPoints: 'STRATEGY POINTS',
    sniperLevels: 'Action Levels',
    idealBuy: 'Ideal Entry',
    secondaryBuy: 'Secondary Entry',
    stopLoss: 'Stop Loss',
    takeProfit: 'Take Profit',
    noValue: '—',
    newsFeed: 'NEWS FEED',
    relatedNews: 'Related News',
    refresh: 'Refresh',
    retry: 'Retry',
    dismiss: 'Close',
    details: 'View details',
    loadingNews: 'Loading news...',
    noNews: 'No related news',
    noNewsDescription: 'Refresh later to check for the latest updates.',
    openLink: 'Open',
    transparency: 'TRANSPARENCY',
    traceability: 'Data Traceability',
    rawResult: 'Raw Analysis Result',
    analysisSnapshot: 'Analysis Snapshot',
    copy: 'Copy',
    copied: 'Copied!',
    recordId: 'Record ID',
    fullReport: 'Full Analysis Report',
    loadingReport: 'Loading report...',
    loadReportFailed: 'failed to load report',
    copyMarkdownSource: 'Copy Markdown Source',
    copyPlainText: 'Copy Plain Text',
    analysisModel: 'Model',
    fearGreedIndex: 'Fear & Greed Index',
    boardLinkage: 'BOARD LINKAGE',
    relatedBoards: 'Related Boards',
    leadingBoard: 'Leading',
    laggingBoard: 'Lagging',
    neutralBoard: 'Neutral',
    reanalyze: 'Reanalyze',
  },
} as const;

export const getReportText = (language?: string | null) => REPORT_TEXT[normalizeReportLanguage(language)];
